### ISSUE TITLE
Help Regarding dlp_mp4base

### ISSUE THREAD

**Issue by DebugPanda** [DolbyLaboratories/dlb_mp4base#30]
Hey Developers,

> I have a question , Please tell me how to run this program/project on Alpine Linux.
    I am really wanted to test this out.

Thanks In Advance…

**Comment by NeedsMoar** [comment]
You'll have to build it first.  Google will explain that.

**Comment by DebugPanda** [comment]
> You'll have to build it first. Google will explain that.

Oh,ok.Thanks mate.

**Comment by NeedsMoar** [comment]
* Technically there is a [linux binary](https://github.com/DolbyLaboratories/dlb_mp4base/blob/master/bin/mp4muxer) in the repo (rather than as a release), but they don't specify whether it's x86 or x64 and this program isn't especially friendly on memory use.    I found it was generally better to just build things like this on linux and optimize for my processor than try to hunt down whatever glibc / glibc++ etc version something was linked against.  Same for Windows really since this project isn't artificially restricted to building only under Cygwin or similar trash.

I only use this project if I need to force-override the dolby vision profile / level on a file to test device support.  [MP4Box](https://github.com/gpac/gpac/wiki/MP4Box) is infinitely more powerful in terms of MP4 standard support of audio types  (adding a thumbnail for NAS, naming streams, auto-converting .srt to .vtt subs) and auto-detects Dolby Vision profile / level info from the video stream passed in now.  It's also an order of magnitude faster and can do in-place updates to file metadata and such.   TSMuxer GUI is the better option for remuxing profile 7 (UHD BD) if you need to do so for some reason.
